# Generated by Django 5.1.1 on 2024-10-28 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('plec', models.CharField(choices=[('M', 'Mezczyzna'), ('K', 'Kobieta'), ('I', 'Inne')], default='M', max_length=1)),
                ('stanowisko', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warsztat_app.stanowisko')),
            ],
        ),
    ]
