# Generated by Django 5.1.1 on 2024-12-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warsztat_app', '0007_delete_user_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_other_person', 'Moze zobaczyc osoby innych włascicieli')], 'verbose_name_plural': 'Osoby'},
        ),
    ]
